export const UI_STRINGS = {
  OVERLAY: {
    TITLE: "ORIENTATION_LOCK",
    MESSAGE: "PLEASE ROTATE DEVICE TO PORTRAIT",
    ERROR_CODE: "ERR: LANDSCAPE_VIEW_UNSUPPORTED"
  },
  SETTINGS: {
    HEADER_TITLE: "KERNEL.CFG",
    HEADER_SUB: "SYS_PREFS_V4.3",
    MEM_OK: "MEM: 64TB OK",
    SECURE_BOOT: "SECURE_BOOT"
  }
};